version: '3.8'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - "./dbdata:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

networks:
  default:
    name: btc-price-guessing
