AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Bitcoin price guessing game backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Runtime: nodejs18.x
    Architectures:
      - x86_64

Resources:
  # Players
  PlayersApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: dist/playersApi
      Handler: handlers/playersApi.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlayersTable
      Events:
        PlayersApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/players/{proxy+}
            Method: ANY

  PlayersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: players

  UpdateBtcPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/btcPriceUpdate
      Handler: handlers/btcPriceUpdate.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PricesTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:btcApiKey-??????"
      Events:
        UpdateBtcPrice:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  PricesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: prices

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PlayersApi:
    Description: "API Gateway endpoint URL for Prod stage for Players API function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/v1/players/"
  PlayersApiFunction:
    Description: "Players API Lambda Function ARN"
    Value: !GetAtt PlayersApiFunction.Arn
  PlayersApiFunctionIamRole:
    Description: "Implicit IAM Role created for Players API function"
    Value: !GetAtt PlayersApiFunctionRole.Arn

  UpdateBtcPriceFunction:
    Description: "Update BTC Price Lambda Function ARN"
    Value: !GetAtt UpdateBtcPriceFunction.Arn
