openapi: 3.0.0
info:
  version: "1.0.0"
  title: Prices API
  description: API endpoint for reading the bitcoin price
paths:
  /v1/prices:
    get:
      summary: get the price of bitcoin
      operationId: getPrice
      description: Get the price of bitcoin in USD
      responses:
        "200":
          description: bitcoin price in usd
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CoinPrice"
        "401":
          description: Unauthorized
        "404":
          description: Not found
      security:
        - jwtAuth: []
    options:
      summary: Options route for CORS
      operationId: getPriceCors
      responses:
        "200":
          description: CORS response
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CoinPrice:
      type: object
      required:
        - value
        - updatedAt
      properties:
        value:
          type: number
          example: 1467.24
        updatedAt:
          type: string
          example: 2022-11-25T12:00:00.000Z
